table _Measure
	lineageTag: ce5f296b-72a7-4035-b97c-a37556082bad

	measure 'Sales by Region' = CALCULATE([Total Sales], DimStore[Region] = "North")
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Sales
		lineageTag: 030bec86-3449-4e61-bd62-3b95a03fab93

	measure 'Total Sales' = SUM(FactSales[Net Sales])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Sales
		lineageTag: 709d265d-1078-4a60-ba30-89c733bf21b7

	measure 'Sales PM' = CALCULATE([Total Sales], DATEADD(DimDate[Date], -1, MONTH))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Sales
		lineageTag: 83cf3bbe-3a58-4663-b233-173ee0d3081a

	measure 'Sales PM Var' = [Total Sales] - [Sales PM]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Sales
		lineageTag: 972b5187-7958-4528-bc37-e00b7e2d0f15

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sales PM Var %' = DIVIDE([Sales PM Var], [Total Sales],0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales
		lineageTag: b932745d-28cb-4e6f-8c04-2d28f5038af3

	measure 'Sales by Store' = ```
			CALCULATE([Total Sales], DimStore[Store])
			
			```
		formatString: 0.00
		displayFolder: Sales
		lineageTag: 3b979f11-0cf0-4d37-83a2-cb912c1e0759

	measure 'Sales Growth %' = ```
			
			VAR PreviousSales = CALCULATE([Total Sales], PREVIOUSMONTH(DimDate[Date]))
			RETURN IF(PreviousSales <> 0, ([Total Sales] - PreviousSales) / PreviousSales, 0)
			
			```
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: Sales
		lineageTag: da4fc639-3ff0-4010-8e53-c0306c6d1b5f

	measure 'Average Sales per Customer' = ```
			DIVIDE([Total Sales], DISTINCTCOUNT(FactSales[CustomerID]))
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Sales
		lineageTag: 9421a983-7c8a-4d60-b852-d98c00ce3b8d

	measure Customer = DISTINCTCOUNT(DimCustomer[CustomerID])
		formatString: 0.00
		lineageTag: 1bcfbbfa-024c-4a2c-b477-4440bd221b65

	measure 'Total Unit price' = SUM(FactSales[UnitPrice])
		lineageTag: 3f526d90-be40-427f-bf22-4e42caaa5f39

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Cost' = sum(FactSales[UnitMakingCost])
		lineageTag: 186f469e-02e0-4eaa-b57c-6029a7a0d558

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = [Total Sales] - [Total Cost]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Profit
		lineageTag: ebf28c60-9af3-4853-a5b2-5e57f7ff2105

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Profit PM' = CALCULATE([Total Profit], DATEADD(DimDate[Date], -1, MONTH))
		displayFolder: Profit
		lineageTag: cf864762-339b-4962-b88a-975a21f23d6e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Per Order' = ```
			
			DIVIDE([Total Profit], DISTINCTCOUNT(FactSales[SalesID]))
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Profit
		lineageTag: 6f37db5f-52f6-4b2b-90c7-bee84681467c

	measure 'Profit Margin %' = ```
			
			DIVIDE([Total Profit], [Total Sales],0)
			
			//Profit Margin % =  DIVIDE([Total Profit], [Total Sales], 0)
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Profit
		lineageTag: e42bc99f-682c-4826-814a-d5bb4b6a86c8

	measure 'Sales MTD' = ```
			CALCULATE([Total Sales], DATESMTD(DimDate[Date]))
			
			```
		displayFolder: Sales
		lineageTag: 7ed62e77-7536-498a-b1c7-54b696c13a62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cumulative / Running Total Sales' = ```
			CALCULATE([Total Sales], FILTER(ALL(DimDate[Date]), DimDate[Date] <= MAX(DimDate[Date])))
			
			```
		displayFolder: Sales
		lineageTag: 9ac37499-fe9b-4fe2-8e63-9e2762694e75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales by Weekday' = ```
			CALCULATE([Total Sales], WEEKDAY(DimDate[Date],2))
			
			```
		displayFolder: Sales
		lineageTag: 5db762d3-da9e-44a1-8ded-f1eecef46d63

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Daily Sales Trend' = ```
			CALCULATE([Total Sales], DAY(DimDate[Date]))
			
			```
		displayFolder: Sales
		lineageTag: 55232293-4a48-4243-989b-b0b3947cb83d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Rating' = AVERAGE(DimCustomer[CustomerRating])
		lineageTag: ab62d8cc-72d7-41fa-9dba-1c5dae969c35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Quantity' = ```
			SUM(FactSales[QuantitySold])
			
			```
		formatString: 0
		lineageTag: a70d4146-221d-47c7-8fb9-3b665ce2cee1

	measure 'QTD Sales' = ```
			TOTALQTD([Total Sales], DimDate[Date])
			
			```
		displayFolder: Sales
		lineageTag: 7249e617-8b6f-43ab-b440-6e70a5850b65

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Rating' = COUNT(DimCustomer[CustomerRating])
		formatString: 0
		lineageTag: 1183f645-2d7c-49bf-b8e7-f36ec0448306

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'QoQ Sales Growth %' = ```
			
			VAR CurrentQuarterSales = [Total Sales]
			VAR PreviousQuarterSales = 
			    CALCULATE(
			        [Total Sales],
			        DATEADD(DimDate[Date], -1, QUARTER)
			    )
			RETURN 
			    IF(
			        NOT ISBLANK(PreviousQuarterSales),
			        DIVIDE(CurrentQuarterSales - PreviousQuarterSales, PreviousQuarterSales),
			        BLANK()
			    )
			```
		lineageTag: 7eb0c3cb-1e66-444b-8a12-cc97693e3e13

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Growth % MoM' = ```
			
			VAR CurrentMonthSales = [Total Sales]
			VAR PreviousMonthSales =
			    CALCULATE(
			        [Total Sales],
			        PREVIOUSMONTH(DimDate[Date])
			    )
			RETURN
			IF(
			    ISBLANK(PreviousMonthSales),
			    0,
			    DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales, 0)
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b6a9a604-2ef9-475a-ac27-964f755abefd

	measure MoM = ```
			VAR Growth=[Sales Growth % MoM]
			RETURN 
			    IF(Growth > 0,"▲ " & FORMAT(Growth,"0.00%"),IF(Growth < 0,"▼ " & FORMAT(Growth,"0.00%"),"→ " & FORMAT(Growth,"0.00%")))
			```
		lineageTag: 66ea256e-3732-416e-82c6-338e817251c4

	measure 'Delay Diff'
		lineageTag: 67062a07-5be6-453e-8099-41a0ba40692b

	measure 'Total Rating Star' = sum(DimCustomer[Rating Star])
		formatString: 0
		lineageTag: cc7b68ac-030c-4971-a2b5-aa5ec86d946d

	measure 'Average Rating Star' = ```
			REPT("⭐", ROUND([Average Rating], 0))
			
			```
		lineageTag: 4e9e75a6-e04b-45de-8364-265e39a9a199

	column Column
		isHidden
		formatString: 0
		lineageTag: 69f0b250-a4df-4152-9d3d-9314b0a0a346
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Measure = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 0b5f4bc37f1240889e615d6e056a7653

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

