table DimCustomer
	lineageTag: 459602c2-cd4b-4b18-a316-13617f20da50

	column CustomerID
		dataType: string
		lineageTag: 44e5e500-2706-4860-9be2-a332ee3ddb99
		summarizeBy: none
		sourceColumn: CustomerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerFeedback
		dataType: string
		lineageTag: ef0d7fbe-2071-4752-9262-108c2ee267cf
		summarizeBy: none
		sourceColumn: CustomerFeedback

		annotation SummarizationSetBy = Automatic

	column CustomerRating
		dataType: int64
		formatString: 0
		lineageTag: 0f4ee669-f971-4d68-90ab-81e0411c3207
		summarizeBy: none
		sourceColumn: CustomerRating

		annotation SummarizationSetBy = Automatic

	column OrderType
		dataType: string
		lineageTag: 387f17a7-a9d0-4551-9542-4919183f59c0
		summarizeBy: none
		sourceColumn: OrderType

		annotation SummarizationSetBy = Automatic

	column PaymentMethod
		dataType: string
		lineageTag: 749f2e4f-884e-4e42-9d1d-2ad3ebaf9556
		summarizeBy: none
		sourceColumn: PaymentMethod

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 3f2af60a-1c3b-49e0-91db-16a8a7f907c7
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Sentiment = ```
			
			SWITCH(
			    TRUE(),
			    SEARCH("delicious", 'DimCustomer'[CustomerFeedback], 1, 0) > 0, "Positive",
			    SEARCH("highly recommend", 'DimCustomer'[CustomerFeedback], 1, 0) > 0, "Positive",
			    SEARCH("amazing", 'DimCustomer'[CustomerFeedback], 1, 0) > 0, "Positive",
			    SEARCH("quick delivery", 'DimCustomer'[CustomerFeedback], 1, 0) > 0, "Positive",
			    SEARCH("perfect", 'DimCustomer'[CustomerFeedback], 1, 0) > 0, "Positive",
			    SEARCH("friendly", 'DimCustomer'[CustomerFeedback], 1, 0) > 0, "Positive",
			    SEARCH("not satisfied", 'DimCustomer'[CustomerFeedback], 1, 0) > 0, "Negative",
			    SEARCH("undercooked", 'DimCustomer'[CustomerFeedback], 1, 0) > 0, "Negative",
			    SEARCH("could improve", 'DimCustomer'[CustomerFeedback], 1, 0) > 0, "Negative",
			    "Neutral"
			)
			
			```
		lineageTag: 04354c98-1284-4fee-a623-d99a73b4ee3d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Rating Label' = ```
			
			SWITCH(
			    DimCustomer[CustomerRating],
			    1, "Rating 1",
			    2, "Rating 2",
			    3, "Rating 3",
			    4, "Rating 4",
			    5, "Rating 5"
			)
			
			```
		lineageTag: 6fa95f5c-ce22-4459-ad05-77de1a248be6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Rating Star' = REPT("⭐",AVERAGE(DimCustomer[CustomerRating]))
		lineageTag: cd774afd-dea8-42d6-9eb7-0e85469ac70d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		source =
				let
				    Source = FlatFile,
				    #"Added Index" = Table.AddIndexColumn(Source, "Index", 1, 1, Int64.Type),
				    #"Inserted Merged Column" = Table.AddColumn(#"Added Index", "StoreKey", each Text.Combine({[Store], [Region], Text.From([Index], "en-US")}, "!!!"), type text),
				    #"Inserted Merged Column1" = Table.AddColumn(#"Inserted Merged Column", "DimProduct", each Text.Combine({[Product], [Category], Text.From([Index], "en-US")}, "|"), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Merged Column1",{{"DimProduct", "ProductID"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"CustomerFeedback", "CustomerRating", "OrderType", "PaymentMethod", "CustomerName", "CustomerID"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"CustomerID", "CustomerFeedback", "CustomerRating", "OrderType", "PaymentMethod", "CustomerName"}),
				    #"Removed Duplicates" = Table.Distinct(#"Reordered Columns", {"CustomerID"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

