table DimDate
	lineageTag: 636ba5c2-fd94-4600-9a33-2d312361f4eb

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1f726657-7df2-4aff-80db-6c5fb4bbfd30
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 69684302-6593-460f-a8d6-2125eb1ef8ca
			defaultHierarchy: LocalDateTable_c70bf1c3-a67c-469c-8c24-2cfa9c268973.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Calendar Year'
		dataType: string
		lineageTag: 5063916f-a1c0-41b1-91e9-10dd08b371c4
		summarizeBy: none
		sourceColumn: Calendar Year

		annotation SummarizationSetBy = Automatic

	column 'Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: ce1a408b-6141-42bb-ad85-e589dc8cf786
		summarizeBy: sum
		sourceColumn: Year Offset

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: 6dd3deb7-c6b8-4ecf-a058-5d327bfffdc5
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: 6e32efe4-502c-481c-b072-2f7ab5f1ea6c
		summarizeBy: sum
		sourceColumn: Fiscal Year Offset

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: a43d3762-fc4c-462c-8e52-e87462d43090
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month'
		dataType: string
		lineageTag: 35237990-032f-4d8d-877d-6fa22d2ff29c
		summarizeBy: none
		sourceColumn: Fiscal Month

		annotation SummarizationSetBy = Automatic

	column 'Month Offset'
		dataType: int64
		formatString: 0
		lineageTag: f8bf5449-2e62-4c9d-af4f-54953b7082d3
		summarizeBy: sum
		sourceColumn: Month Offset

		annotation SummarizationSetBy = Automatic

	column 'Month Status'
		dataType: string
		lineageTag: 4dc3fc58-6305-4340-a89e-d2cdc7018c12
		summarizeBy: none
		sourceColumn: Month Status

		annotation SummarizationSetBy = Automatic

	column LTM
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6ac6e13c-b3b4-4ab4-a6f0-8cfefd47dd6f
		summarizeBy: none
		sourceColumn: LTM

		annotation SummarizationSetBy = Automatic

	column PeriodNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: d3b3efdf-2d4d-420c-8924-8cca260bf65f
		summarizeBy: sum
		sourceColumn: PeriodNumberOfYear

		annotation SummarizationSetBy = Automatic

	column MonthNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: cd2a04a2-4ed9-4604-84d4-05481a1b8b0d
		summarizeBy: sum
		sourceColumn: MonthNumberOfYear

		annotation SummarizationSetBy = Automatic

	column MonthLongName
		dataType: string
		lineageTag: 602926c4-1a11-4fa5-bac0-90fd2b606e61
		summarizeBy: none
		sourceColumn: MonthLongName

		annotation SummarizationSetBy = Automatic

	column MonthShortName
		dataType: string
		lineageTag: 7c7e926b-5584-478e-849a-e02fa3597cd0
		summarizeBy: none
		sourceColumn: MonthShortName
		sortByColumn: MonthNumberOfYear

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: string
		lineageTag: 5fdb42d8-dab7-44f3-aff9-1f5377eb92ba
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e6f3ff77-e784-4e93-866f-edac77426e25
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: ce1c81d2-e306-49d9-a5f8-902758fd5a03
		summarizeBy: sum
		sourceColumn: QuarterNumberOfYear

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Offset'
		dataType: int64
		formatString: 0
		lineageTag: 19fc7717-0c88-417d-b704-9985af498ae0
		summarizeBy: sum
		sourceColumn: Fiscal Quarter Offset

		annotation SummarizationSetBy = Automatic

	column StartOfWeek
		dataType: string
		lineageTag: c3f00cf2-5a8d-4c33-8ee0-e4adbcad0e0f
		summarizeBy: none
		sourceColumn: StartOfWeek

		annotation SummarizationSetBy = Automatic

	column WeekName
		dataType: string
		lineageTag: 1a104d6b-d60c-47b5-8fb9-32233efe31b4
		summarizeBy: none
		sourceColumn: WeekName

		annotation SummarizationSetBy = Automatic

	column 'Week Offset'
		dataType: int64
		formatString: 0
		lineageTag: dd51c04f-ccda-4e40-93a1-7b69a3263224
		summarizeBy: sum
		sourceColumn: Week Offset

		annotation SummarizationSetBy = Automatic

	column 'Day Offset'
		dataType: int64
		formatString: 0
		lineageTag: 82ffba77-1caf-4d41-ac17-91d313bfd494
		summarizeBy: sum
		sourceColumn: Day Offset

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: int64
		formatString: 0
		lineageTag: dbc49dfb-a737-42e0-ae08-c4ade7f60365
		summarizeBy: sum
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: string
		lineageTag: 876518d8-4632-4fc4-8bd7-c08e856f942b
		summarizeBy: none
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column WeekdayShortName
		dataType: string
		lineageTag: 894da6f9-12bf-4c29-a859-2d21fbfbb25a
		summarizeBy: none
		sourceColumn: WeekdayShortName

		annotation SummarizationSetBy = Automatic

	column WeekdayNumber
		dataType: int64
		formatString: 0
		lineageTag: 799a4a92-df2d-43a9-be7f-e3252a49e258
		summarizeBy: sum
		sourceColumn: WeekdayNumber

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 16f9f78b-917a-4100-afcc-f33b7b706638
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column 'Half Year'
		dataType: string
		lineageTag: 380afbfb-6195-4884-b49b-4633d57806c0
		summarizeBy: none
		sourceColumn: Half Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Half Year'
		dataType: string
		lineageTag: f0cd929e-5a80-43d9-a847-16a5a23c9382
		summarizeBy: none
		sourceColumn: Fiscal Half Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Half Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: c894fc5c-9273-497d-8b84-77e9c9985582
		summarizeBy: sum
		sourceColumn: Fiscal Half Year Offset

		annotation SummarizationSetBy = Automatic

	column ShipDate = ```
			DimDate[Date] + 7
			
			```
		isHidden
		formatString: Long Date
		lineageTag: 530ae85a-a248-4c3c-9641-0a3d0eac1b8d
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 9626eddf-13d1-454a-bcf9-acd8d333a050
			defaultHierarchy: LocalDateTable_35bf8692-acde-4fb7-a27a-f4c056f16d35.'Date Hierarchy'

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderDate = ```
			DimDate[Date] + 4
			
			```
		isHidden
		formatString: Long Date
		lineageTag: f79a0481-2dc4-4bf7-9bd4-362317ef586c
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 742be7de-6545-4b1d-b30e-38ee5517cfef
			defaultHierarchy: LocalDateTable_a851f161-8615-4dfa-952f-5ecb2f0712ef.'Date Hierarchy'

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DimDate = m
		mode: import
		source = ```
				let
				    ListDates = List.Dates(#"StartDate", Number.From(#"EndDate" - #"StartDate")+1, #duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(ListDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Added Calendar Date" = Table.AddColumn(#"Renamed Columns", "Calendar Date", each Date.AddMonths ([Date],#"Fiscal Year Reset")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Calendar Date",{{"Date", type date}, {"Calendar Date", type date}}),
				    #"Month Offset" = Table.AddColumn(#"Changed Type", "Month Offset", each (Date.Year([Date]) - Date.Year(Date.From(DateTime.LocalNow())))*12 
				+ Date.Month([Date]) - Date.Month(Date.From(DateTime.LocalNow()))),
				    #"Day Offset" = Table.AddColumn(#"Month Offset", "Day Offset", each Number.From((Date.From(DateTime.LocalNow()) - [Date])) * -1, type number),
				    #"Year Offset" = Table.AddColumn(#"Day Offset", "Year Offset", each (Date.Year(Date.From(DateTime.LocalNow())) - Date.Year([Date])) * -1),
				    #"Fiscal Year Offset" = Table.AddColumn(#"Year Offset", "Fiscal Year Offset", each if Date.Month(Date.From(DateTime.LocalNow())) > (12-#"Fiscal Year Reset")
				
				then 
				((Date.Year(Date.From(DateTime.LocalNow())) - Date.Year([Calendar Date])) * -1) -1
				
				else 
				
				(Date.Year(Date.From(DateTime.LocalNow())) - Date.Year([Calendar Date])) * -1),
				    #"Inserted Calendar Year" = Table.AddColumn(#"Fiscal Year Offset", "Calendar Year", each Date.Year([Date])),
				    #"Fiscal Year" = Table.AddColumn(#"Inserted Calendar Year", "Fiscal Year", each "FY" & Date.ToText([Calendar Date], "yy")),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Fiscal Year",{{"Year Offset", Int64.Type}, {"Calendar Year", type text}, {"Fiscal Year", type text}, {"Fiscal Year Offset", Int64.Type}}),
				    PeriodNumberOfYear = Table.AddColumn(#"Changed Type1" , "PeriodNumberOfYear", each Date.Month([Calendar Date])),
				    MonthNumberOfYear = Table.AddColumn(PeriodNumberOfYear, "MonthNumberOfYear", each Date.Month([Date]), Int64.Type),
				    MonthLongName = Table.AddColumn(MonthNumberOfYear, "MonthLongName", each Date.MonthName([Date]), type text),
				    MonthShortName = Table.AddColumn(MonthLongName, "MonthShortName", each Text.Start([MonthLongName], 3), type text),
				    #"Month Status" = Table.AddColumn(MonthShortName, "Month Status", each if [Month Offset] = 0 then " Current" else if [Month Offset] > 0 then "Future" else "Complete"),
				    Month = Table.AddColumn(#"Month Status", "Month", each [MonthShortName]
				 &" '"& 
				 Date.ToText([Date], "yy")),
				    #"Fiscal Month" = Table.AddColumn(Month, "Fiscal Month", each [MonthShortName]
				 &", "& 
				[Fiscal Year]),
				    #"Added LTM" = Table.AddColumn(#"Fiscal Month", "LTM", each if [Month Offset] > -13 and [Month Offset] < 0
				 then "True"
				 else "False"),
				    #"Fiscal Quarter" = Table.AddColumn(#"Added LTM", "Quarter", each "Q"& Text.From(Date.QuarterOfYear([Calendar Date]))),
				    #"Added QuarterNumberOfYear" = Table.AddColumn(#"Fiscal Quarter", "QuarterNumberOfYear", each Date.QuarterOfYear([Calendar Date])),
				    #"Fiscal Quarter Year" = Table.AddColumn(#"Added QuarterNumberOfYear", "Fiscal Quarter", each [Quarter]
				 &" '"& 
				 [Fiscal Year]),
				    #"Fiscal Quarter Offset" = Table.AddColumn(#"Fiscal Quarter Year", "Fiscal Quarter Offset", each ( Date.Year (Date.AddMonths([Date],#"Fiscal Year Reset")) 
				  - 
				   Date.Year(
				       Date.From(Date.AddMonths( DateTime.LocalNow(), #"Fiscal Year Reset") )
				            )
				  )*4 
				
				+ Date.QuarterOfYear (Date.AddMonths([Date],#"Fiscal Year Reset")) 
				
				- Date.QuarterOfYear (Date.AddMonths( DateTime.LocalNow(), #"Fiscal Year Reset"))),
				    #"Inserted DayOfMonth" = Table.AddColumn(#"Fiscal Quarter Offset", "DayOfMonth", each Date.Day([Date]), type number),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted DayOfMonth", "Weekday", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted WeekdayShortName" = Table.AddColumn(#"Inserted Day Name", "WeekdayShortName", each Text.Start([Weekday], 3), type text),
				    #"Inserted WeekDayNumber" = Table.AddColumn(#"Inserted WeekdayShortName", "WeekdayNumber", each Date.DayOfWeek([Date]), type number),
				    IsWeekend = Table.AddColumn(#"Inserted WeekDayNumber", "IsWeekend", each Logical.From(if [WeekdayNumber]= 6 or [WeekdayNumber] = 0 then "TRUE" else "FALSE")),
				    #"Inserted End of Week" = Table.AddColumn(IsWeekend, "StartOfWeek", each Date.StartOfWeek([Date], Day.Monday)),
				    #"Added WeekName" = Table.AddColumn(#"Inserted End of Week", "WeekName", each Text.Combine
				(
				 {
				  "Week of ",
				  Date.ToText([StartOfWeek], "MMM"),
				
				  "-",
				  Date.ToText([StartOfWeek], "dd"),
				  ", '",
				  Date.ToText([StartOfWeek], "yy")
				  }
				)),
				    #"Week Offset" = Table.AddColumn(#"Added WeekName", "Week Offset", each (
				    Number.From((Date.From(Date.EndOfWeek(DateTime.LocalNow(), Day.Monday)) - [StartOfWeek]))
				 * -1) 
				 / 7),
				    #"Half Year" = Table.AddColumn(#"Week Offset", "Half Year", each if Number.RoundUp([PeriodNumberOfYear]/6)=1
				then "1st Half"
				else "2nd Half"),
				    #"Fiscal Half Year" = Table.AddColumn(#"Half Year", "Fiscal Half Year", each [Fiscal Year]&" "&[Half Year]),
				    #"Fiscal Half Year Offset" = Table.AddColumn(#"Fiscal Half Year", "Fiscal Half Year Offset", each [Fiscal Year Offset]*2
				
				+ 
				Number.RoundUp(
				(Date.Month([Calendar Date]) - Date.Month(Date.From(DateTime.LocalNow())))/6
				)-1),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Fiscal Half Year Offset",{{"Week Offset", type number}}),
				    #"Rounded Down" = Table.TransformColumns(#"Changed Type2",{{"Week Offset", Number.RoundDown, Int64.Type}}),
				    #"Sorted Rows" = Table.Sort(#"Rounded Down",{{"Date", Order.Ascending}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Sorted Rows",{"Date", "Month Offset", "Day Offset", "Year Offset", "Fiscal Year Offset", "Calendar Year", "Fiscal Year", "PeriodNumberOfYear", "MonthNumberOfYear", "MonthLongName", "MonthShortName", "Month Status", "Month", "Fiscal Month", "LTM", "Quarter", "QuarterNumberOfYear", "Fiscal Quarter", "Fiscal Quarter Offset", "DayOfMonth", "Weekday", "WeekdayShortName", "WeekdayNumber", "IsWeekend", "StartOfWeek", "WeekName", "Week Offset", "Half Year", "Fiscal Half Year", "Fiscal Half Year Offset"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"Date", "Calendar Year", "Year Offset", "Fiscal Year", "Fiscal Year Offset", "Month", "Fiscal Month", "Month Offset", "Month Status", "LTM", "PeriodNumberOfYear", "MonthNumberOfYear", "MonthLongName", "MonthShortName", "Fiscal Quarter", "Quarter", "QuarterNumberOfYear", "Fiscal Quarter Offset", "StartOfWeek", "WeekName", "Week Offset", "Day Offset", "DayOfMonth", "Weekday", "WeekdayShortName", "WeekdayNumber", "IsWeekend"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Reordered Columns",{{"Calendar Year", type text}, {"Year Offset", Int64.Type}, {"Fiscal Year", type text}, {"Fiscal Year Offset", Int64.Type}, {"Month Status", type text}, {"Fiscal Month", type text}, {"Month", type text}, {"Month Offset", Int64.Type}, {"LTM", type logical}, {"PeriodNumberOfYear", Int64.Type}, {"MonthNumberOfYear", Int64.Type}, {"MonthLongName", type text}, {"MonthShortName", type text}, {"Fiscal Quarter", type text}, {"Quarter", type text}, {"QuarterNumberOfYear", Int64.Type}, {"Fiscal Quarter Offset", Int64.Type}, {"Week Offset", Int64.Type}, {"StartOfWeek", type text}, {"WeekName", type text}, {"Day Offset", Int64.Type}, {"DayOfMonth", Int64.Type}, {"WeekdayNumber", Int64.Type}, {"Weekday", type text}, {"WeekdayShortName", type text}, {"IsWeekend", type logical}, {"Half Year", type text}, {"Fiscal Half Year", type text}, {"Fiscal Half Year Offset", Int64.Type}}),
				    #"Sorted Rows1" = Table.Sort(#"Changed Type3",{{"Date", Order.Descending}})
				in
				    #"Sorted Rows1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

