table FactSales
	lineageTag: 4758c0f2-09f7-411e-8a88-ec884baa2f33

	column SalesID
		dataType: string
		lineageTag: eaded429-e44a-4699-92d7-554cfa8d2993
		summarizeBy: none
		sourceColumn: SalesID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5076ca9c-658c-4fbd-8f19-4111daefe8c2
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column QuantitySold
		dataType: int64
		formatString: 0
		lineageTag: 78de0840-d671-42b0-a932-c6e2e6cd1f0c
		summarizeBy: sum
		sourceColumn: QuantitySold

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 9cfa519f-408a-4fb2-9eed-46a679d6aac0
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerID
		dataType: string
		lineageTag: 53e671a5-71a2-4d3c-a308-19f0a3a88ead
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column UnitMakingCost
		dataType: double
		lineageTag: e453e956-eb3f-4e57-bcee-99a333ce436d
		summarizeBy: sum
		sourceColumn: UnitMakingCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StoreKey
		dataType: string
		lineageTag: 5dc0bb4d-2fe8-464e-84db-e36e794cef86
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		lineageTag: 85fbe0e1-e60f-4da5-b889-18613df4d23e
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: string
		lineageTag: d0b85103-89b0-4fda-a6b2-7c24d4563c37
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: string
		lineageTag: af9ee0df-f506-4f9e-8ae1-276184d93d98
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales' = (FactSales[QuantitySold] * FactSales[UnitPrice])
		lineageTag: 3204aefb-ae58-4b22-bde7-ccfb4cea3893
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Sales' = FactSales[Gross Sales] - FactSales[UnitMakingCost]
		lineageTag: e5bdd418-80d4-48fd-8cf1-a9d22b1fcb7c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Store
		dataType: string
		lineageTag: a60f36df-077c-4873-9cc2-473ce46ab45c
		summarizeBy: none
		sourceColumn: Store

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b20b2cfc-098d-4370-bc57-825703575771
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition FactSales = m
		mode: import
		source =
				let
				    Source = FlatFile,
				    #"Added Index" = Table.AddIndexColumn(Source, "Index", 1, 1, Int64.Type),
				    #"Inserted Merged Column" = Table.AddColumn(#"Added Index", "StoreKey", each Text.Combine({[Store], [Region], Text.From([Index], "en-US")}, "!!!"), type text),
				    #"Inserted Merged Column1" = Table.AddColumn(#"Inserted Merged Column", "DimProduct", each Text.Combine({[Product], [Category], Text.From([Index], "en-US")}, "|"), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Merged Column1",{{"DimProduct", "ProductID"}}),
				    #"Sorted Rows" = Table.Sort(#"Renamed Columns",{{"Date", Order.Ascending}}),
				    #"Added Custom" = Table.AddColumn(#"Sorted Rows", "ShipDate", each Date.AddDays([Date], 7)),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "OrderDate", each Date.AddDays([Date], 4)),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom1",{"Product", "Category", "PaymentMethod", "CustomerName", "OrderType", "CustomerRating", "CustomerFeedback", "Index"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

